=head1 NAME

gedafe-search - Searching in gedafe.

=head1 STATUS

Testing

=head1 DESCRIPTION



=head1 USAGE

Search questions can be entered into multiple rows.
These rows are joined by AND operators into the
query to the database.
Per field you can enter multiple words. These are
also joined by an AND operator.
Individual fields can also contain the OR operator.

To remove a line of search questions just clear the
textbox next to it.
 

Example:

foo bar   <=> foo AND bar

foo OR bar    <=> foo OR BAR (unchanged)



=head1 Operators

A question may be preceded by a comparison operator:


Example:

> 5

not apple



These operators are supported:


Operator:	What it does:

----------------------------------------

 =	-> 	compare char by char

 >= 	-> 	>=

 <= 	->	<=

 ~* 	->	=~

 =~	->	=~

 > 	->	>

 < 	->	<

 	->	finds needle in haystack*
  
* this is the default behaviour when no operator
is specified.
 


=head1 Bytea columns

Unfortunately we can't search bytea columns yet.


=head1 COPYRIGHT

Copyright (c) 2004 Freek Zindel, All rights reserved.


=head1 LICENSE

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

=head1 AUTHOR

S<Freek Zindel E<lt>freek@zindel.nlE<gt>>


